### PR TITLE
Dakota/prettify git -> main

### PR DESCRIPTION
**Pull request by Da-Scher**
Related issue: #10
Quick Message: This PR will require everybody to agree to the wording of their entry in Main Contributors. It is expected that the wording of people is a mistake on my part until you agree by accepting the merge request. Please correct me if they are wrong.

Explanation of changes:
I added a logo file to this repository image hosting server and made that logo appear at the top of the README.md file. I also added a Major Contributors entry in README.md that lists everybody's cool cam on this project.

### CODE REVIEW

**Review by justinsprecco — COMMENTED** [review]
What is the dist folder going to be used for?

**Comment by Da-Scher** [comment]
> What is the dist folder going to be used for?

The dist folder is the build folder. We don't want to push the built application to the repo because git will not compress it. We will start using releases for that later.

**Review by justinsprecco — APPROVED** [review]
Everything looks good.

**Review by joebarteluce — APPROVED** [review]
The wording of the readme looks good.

**Pull request merged**
