### PR TITLE
Joe/video gallery

### PR DESCRIPTION
**Pull request by joebarteluce**
Added a video player component which utilizes video.js.

### CODE REVIEW

**Review by Da-Scher — APPROVED** [review]
LGTM :+1:

**Comment by Da-Scher** [comment]
Please assign to an issue and assign the issue to your midterm milestone so we look really cool.

**Review by justinsprecco — APPROVED** [review]
Looks great!

**Review by Da-Scher — APPROVED** [review]
Looks cool to me!
:sunglasses:

**Review by Da-Scher — APPROVED** [review]
All issues fixed:
node packages installing,
angular building,
Peter Parker is spiderman
LGTM :+1:

**Pull request merged**
